name: alephium_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  retrofit: ">=3.0.0 <4.0.0"
  bs58: ^1.0.2
  encrypt:
    git: https://github.com/leocavalcante/encrypt.git
  bip39: ^1.0.6
  bip32: ^2.0.0
  ecdsa:
    git: https://github.com/sahharYoucef/dart-ecdsa.git
  dio: 4.0.4
  json_annotation: 4.7.0

#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.0
  json_serializable: 6.5.4
  retrofit_generator: any
